version: '3'
services:
  mongo:
    container_name: mongo_db
    image: mongo
    ports:
      - '27017:27017'
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - '3000:3000'
      - '4000:4000'
    external_links:
        - mongo
